version: '3'
services:
  netdata_monitor:
    image: manoskoutoulakis/netdata_nginx:latest
    environment:
      - ID=${NETDATA_ID}
    ports:
      - 19998:19998
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: "obc_source_monitoring"
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${EXECUTOR_DB_PORT}:5432"
    container_name: "local_executor_db_${EXECUTOR_INSTANCE}"

  airflowserver:
    # image: manoskoutoulakis/docker-obc-airflow:1.10.9
    build: 
      context: .
      dockerfile: airflow.Dockerfile
    restart: always
    depends_on:
      - postgres
      - netdata_monitor
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:${EXECUTOR_DB_PORT}/airflow
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080/${OBC_USER_ID}
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
      #OBC Client environment variables
      - OBC_USER_ID=${OBC_USER_ID}
      - PUBLIC_IP=${PUBLIC_IP}
      - EXECUTOR_INSTANCE=${EXECUTOR_INSTANCE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - NETDATA_MONITORING_PORT=${NETDATA_MONITORING_PORT}
      - OBC_EXECUTOR_PORT=${OBC_EXECUTOR_PORT}
      - OBC_AIRFLOW_PORT=${OBC_AIRFLOW_PORT}
      - EXECUTOR_DB_PORT=${EXECUTOR_DB_PORT}
      - FLASK_ENV=development
      - NETDATA_ID=${NETDATA_ID}
    volumes:
      # Folder where airflow should store files
      - dagvolume:/usr/local/airflow/dags
      - logvolume:/usr/local/airflow/logs
      - reportvolume:/usr/local/airflow/REPORTS
      # Configuration File
      - ./airflow.cfg:/usr/local/airflow/airflow.cfg
      - /var/run/docker.sock:/var/run/docker.sock
      - ./client/client/templates:/usr/local/airflow/templates/
      - ./client/client/static:/usr/local/airflow/static/
      - ./client/client/client.py:/usr/local/airflow/client.py
      # For custom plugins
      #- ./plugins:/usr/local/airflow/plugins
    ports:
      - "${OBC_AIRFLOW_PORT}:8080"
      - "${OBC_EXECUTOR_PORT}:5000"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 15s
      timeout: 15s
      retries: 3
    container_name: "executor_airflow_${EXECUTOR_INSTANCE}"
volumes:
  # Dag volumes 
  dagvolume:
  logvolume:
  reportvolume:  
  




