version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
  restapi:
    image: manoskoutoulakis/obc_client:latest
    depends_on:
      - postgres
      - airflowserver
    restart: always
    volumes:
      # docker connect with client to get info or execute commands
      - /var/run/docker.sock:/var/run/docker.sock
      # volume which share data with airflow
      - dagvolume:/code/generated_dags
    ports:
      - "5000:5000"

  airflowserver:
    image: puckel/docker-airflow:1.10.1
    build:
      context: https://github.com/puckel/docker-airflow.git#1.10.1
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: gcp_api,s3
        PYTHON_DEPS: sqlalchemy==1.2.0
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
    volumes:
      # Volume which share data with client
      - dagvolume:/usr/local/airflow/dags
      # Folder where airflow should store its log files
      #- ./logs:/usr/local/airflow/logs
      # Configuration File
      #- ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
      - /var/run/docker.sock:/var/run/docker.sock
      # For custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 15s
      timeout: 15s
      retries: 3
volumes:
  # client-airflow dags volume
  dagvolume:
